resources:

- name: repo
  type: git
  source:
    uri: https://github.com/ndarilek/concourse-npm-resource
    branch: master

- name: image
  type: docker-image
  source:
    username: {{registry_username}}
    email: {{registry_email}}
    password: {{registry_password}}
    repository: nolan/concourse-npm-resource

jobs:

- name: test
  public: true
  plan:

  - get: repo
    trigger: true

  - task: run tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node, tag: "5"}
      inputs:
        - name: repo
      run:
        path: sh
        args:
          - -exc
          - |
            cd repo
            npm test

- name: build
  public: true
  plan:

  - get: repo
    passed: [test]
    trigger: true

  - put: image
    params:
      build: repo
